### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by Aleck85** [Narno/F-Notifier#35]
Does not work. Ff 90/ 
![Снимок экрана (3)](https://user-images.githubusercontent.com/5072865/128402095-0a00f74b-f987-4809-a812-f59ddfc57d1c.png)

**Comment by xshinox** [comment]
Can confirm. Does not work for me as well. On FireFox version 90.0.2 (64-bit). The update probably messed up this extension

**Comment by Aleck85** [comment]
Does not work in chrome/microsoft edge as well. The same result. 
![Снимок экрана (5)](https://user-images.githubusercontent.com/5072865/128588425-472cf921-e51b-4cb1-8674-a7ace5700782.png)

**Comment by Aleck85** [comment]
In Microsoft Edge doesn't work as well. Please fix it.

**Comment by Narno** [comment]
Hello, it should be fixed in the next release (Pending review).

**Comment by Narno** [comment]
Version 2.6.0 published.

**Comment by Aleck85** [comment]
Still not working.
![Снимок](https://user-images.githubusercontent.com/5072865/131799753-3ed59576-f4aa-46ec-bb95-7e087bf35b75.JPG)

**Comment by Aleck85** [comment]
No, it was likes and mentions.
![Снимок](https://user-images.githubusercontent.com/5072865/131955768-eaca1ec4-92c4-447b-8e6f-31a795fc77b1.JPG)

**Comment by Aleck85** [comment]
Friend request, for example. With the other extension it works well.
![Снимок1](https://user-images.githubusercontent.com/5072865/131958667-0a47d33c-05ac-4036-9a05-bc88c12905be.JPG)

**Comment by Narno** [comment]
Hello Aleck85, I have finally rebuild a part of the extension with a new scraping method: the extension now use `m.facebook.com` instead of `mbasic.faceook.com`.

I think it's much better 🤞

Could you try the last version (2.7.0)?

**Comment by Aleck85** [comment]
Hello. Unfortunately I won't be able to test Firefox version until Tuesday. Now 2.7.0 for Chrome is working in Microsoft Edge too.

**Comment by Aleck85** [comment]
Yes, now it works correctly.
![Снимок экрана 2021-09-06 191754](https://user-images.githubusercontent.com/5072865/132244264-39e77490-7f40-4a89-b9eb-c3746d90d9f3.jpg)
